CREATE TABLE crmmdm.EXTENDED_LTC_AGGR(
	TOUCH_DT DATE,
	ORDER_ID VARCHAR(50),
	LAST_TOUCH_CHNL VARCHAR(50),
	MOBILE_DEVICE_TYPE VARCHAR(50),
	MESSAGE_ID VARCHAR(50),
	COUPON_CD VARCHAR(50),
	DOMAIN_NAME VARCHAR(50),
	VISIT_REFERRER VARCHAR(50),
	FIRST_HIT_REFERRER VARCHAR(50),
	GEO_CITY VARCHAR(50),
	GEO_COUNTRY VARCHAR(50),
	GEO_REGION VARCHAR(50),
	POST_CAMPAIGN VARCHAR(50),
	PAYMENT_METHOD VARCHAR(50),
	BRAND_CD VARCHAR(50),
	REVENUE NUMERIC(38,6),
	UNITS NUMERIC(38,2),
	GIFT_CARD_AMOUNT_USED NUMERIC(38,2),
	PROMOTIONAL_AMNT NUMERIC(38,2),
	SHIPPING_COST NUMERIC(38,6),
	TAX_AMNT NUMERIC(38,6),
	COUPON_DSCNT NUMERIC(38,6),
	);

CREATE TABLE IF NOT EXISTS crmmdm.ECOM_CUST_BRIDGE
(
  ECOM_ORD_ID_PK VARCHAR(25) NOT NULL,
  EMAIL_ADDR VARCHAR(75),
  EMAIL_ID INTEGER,
  CUST_ID INTEGER NOT NULL,
  LANDING_BRAND_ORIG VARCHAR(10),
  DEVICE_TYPE_ORIG VARCHAR(30),
  LTC_ORIG VARCHAR(300),
  TOUCH_DT_ORIG DATE,
  POST_CAMPAIGN_ORIG VARCHAR(300),
  CID_LW_CHANNEL VARCHAR(300),
  CID_PUBLISHER VARCHAR(300),
  CID_BRAND_OTHERS VARCHAR(300),
  CID_KYD_OTHERS VARCHAR(300),
  CID_BRANDALONE_OTHERS VARCHAR(300),
  LTC_EXTENDED VARCHAR(300),
  LTC_DERIVED VARCHAR(300) NOT NULL,
  LANDING_BRAND_DERIVED VARCHAR(10),
  DEVICE_TYPE_DERIVED VARCHAR(30)
);


CREATE TABLE crmmdm.ECOM_BRAND_KPI
(
	ECOM_ORDER_ID_PK VARCHAR(50)  NOT NULL,
	DIVISION_NUMBER VARCHAR(2) NOT NULL,
	BRAND_CODE VARCHAR(10),
	ORD_DT DATE NOT NULL,
	NET_SLS_LCY NUMERIC(38,2),
    NET_SLS_BOY_LCY NUMERIC(38,2),
    NET_SLS_GIRL_LCY NUMERIC(38,2),
    NET_SLS_UNISEX_LCY NUMERIC(38,2),
	COST_LCY NUMERIC(38,6),
	UNITS NUMERIC(38,2)
	) DISTKEY(ECOM_ORDER_ID_PK);
	
CREATE TABLE IF NOT EXISTS crmmdm.TRN_CUST_BRIDGE
(
  TRN_ID BIGINT NOT NULL
 ,CUST_ID INTEGER NOT NULL
 ,EMAIL_ADDR VARCHAR(75)
 ,EMAIL_ID INTEGER
 ,PURCHASE_DT DATE NOT NULL
 ,PURCHASE_AMT NUMERIC(11,5) NOT NULL
 ,TRN_VOID_IND VARCHAR(1)
 ,TRN_TYPE VARCHAR(10)
)


CREATE TABLE IF NOT EXISTS crmmdm.CUST_PURCHASE_AGGREGATE
(
  EMAIL_ID INTEGER
 ,EMAIL_ADDR VARCHAR(75)
 ,CUST_ID INTEGER NOT NULL
 ,GENERIC_ARTCL_NUMBER VARCHAR(30) NOT NULL
 ,GENERIC_ARTCL_DESCRIPTION VARCHAR(40)
 ,DEPARTMENT_DIVISION_NAME VARCHAR(40) NOT NULL
 ,PURCHASE_DT DATE NOT NULL
 ,TOT_PURCHASE_AMT_USD NUMERIC(11,5)
)

CREATE TABLE IF NOT EXISTS crmmdm.TELECOM_AGGREGATE
(
  TELECOM_ID INTEGER NOT NULL
 ,TELECOM_NUMBER INTEGER NOT NULL
 ,CUST_ID BIGINT
 ,EMAIL_ID INTEGER
 ,SMS_FOR_D13_D33AT_TYPE VARCHAR(2) NOT NULL
 ,SMS_FORMAT_TYPE_NUMERIC INTEGER
 ,INDIV_FORMAT_TYPE_ALPHA1 VARCHAR(2)
 ,INDIV_FORMAT_TYPE_ALPHA2 VARCHAR(2)
 ,LST_OPT_IN_DATE DATE
 ,TCP_OPT_IN_DATE DATE
 ,TCP_OPT_OUT_DATE DATE
 ,TCP_OPT_IN_STATUS VARCHAR(2)
 ,TCP_US_OPT_IN_DATE  DATE
 ,TCP_US_OPT_OUT_DATE DATE
 ,TCP_US_OPT_IN_STATUS VARCHAR(2)
 ,TCP_CA_OPT_IN_DATE DATE
 ,TCP_CA_OPT_OUT_DATE DATE
 ,TCP_CA_OPT_IN_STATUS VARCHAR(2)
 ,GYM_OPT_IN_DATE DATE
 ,GYM_OPT_OUT_DATE DATE
 ,GYM_OPT_IN_STATUS VARCHAR(2)
 ,TRANSACTIONLIST_OPT_IN_DATE DATE
 ,TRANSACTIONLIST_OPT_OUT_DATE DATE
 ,TRANSACTIONLIST_OPT_IN_STATUS VARCHAR(2)
 ,SUBSCRIPTION_BRAND VARCHAR(2)
 ,LAST_CLICK_DATE  DATE
 ,TOTAL_CLICKS INTEGER
 ,TOTAL_CLICKS_LAST_6MNTHS INTEGER
 ,NTF_FLG_TCP VARCHAR(1)
 ,NTF_FLG_GYM VARCHAR(1)
 ,NTF_PURCHASER_FLG_TCP VARCHAR(1)
 ,NTF_PURCHASER_FLG_GYM VARCHAR(1)
 ,NTF_NON_PURCHASER_FLG_TCP VARCHAR(1)
 ,NTF_NON_PURCHASER_FLG_GYM VARCHAR(1)
 )

CREATE TABLE IF NOT EXISTS crmmdm.CUSTOMER_AGGREGATE
(
CUST_ID	BIGINT NOT NULL
,ORIG_ACQUIRED_BRAND	VARCHAR(5)
,ACQUIRED_BRANDS	VARCHAR(30)
,AFFILIATED_BRANDS	VARCHAR(30)
,LAST_BOSS_DT_TCP	DATE
,LAST_BOSS_DT_GYM	DATE
,LAST_BOPIS_DT_TCP	DATE
,LAST_BOPIS_DT_GYM	DATE
,NBR_BOSS_PURCH_L2Y_TCP	INTEGER
,NBR_BOSS_PURCH_L2Y_GYM	INTEGER
,NBR_BOPIS_PURCH_L2Y_TCP	INTEGER
,NBR_BOPIS_PURCH_L2Y_GYM	INTEGER
,CHILD_GENDER_TCP	VARCHAR(5)
,CHILD_GENDER_GYM	VARCHAR(5)
,FIRST_PURCH_DT	DATE
,FIRST_PURCH_DT_TCP	DATE
,FIRST_PURCH_DT_GYM	DATE
,LAST_PURCH_DT	DATE
,LAST_PURCH_DT_TCP	DATE
,LAST_PURCH_DT_GYM	DATE
,FIRST_ECOM_PURCH_DT	DATE
,FIRST_ECOM_PURCH_DT_TCP	DATE
,FIRST_ECOM_PURCH_DT_GYM	DATE
,LAST_ECOM_PURCH_DT	DATE
,LAST_ECOM_PURCH_DT_TCP	DATE
,LAST_ECOM_PURCH_DT_GYM	DATE
,TOT_NBR_PURCH	INTEGER
,TOT_NBR_PURCH_TCP	INTEGER
,TOT_NBR_PURCH_GYM	INTEGER
,TOT_NBR_ECOM_PURCH	INTEGER
,TOT_NBR_ECOM_PURCH_TCP	INTEGER
,TOT_NBR_ECOM_PURCH_GYM	INTEGER
,NET_SPEND_ECOM	NUMERIC(38,2)
,NET_SPEND_ECOM_TCP	NUMERIC(38,2)
,NET_SPEND_ECOM_GYM	NUMERIC(38,2)
,NET_SPEND_TY	NUMERIC(38,2)
,NET_SPEND_TY_TCP	NUMERIC(38,2)
,NET_SPEND_TY_GYM	NUMERIC(38,2)
,NET_SPEND_LIFETIME	NUMERIC(38,2)
,NET_SPEND_LIFETIME_TCP	NUMERIC(38,2)
,NET_SPEND_LIFETIME_GYM	NUMERIC(38,2)
,NET_SPEND_ECOM_TY	NUMERIC(38,2)
,TOT_NBR_ECOM_PURCH_TY	INTEGER
,TOT_NBR_PURCH_TY	INTEGER
,SPEND_BOY_TY	NUMERIC(38,2)
,SPEND_GIRL_TY	NUMERIC(38,2)
,SPEND_NEWBORN_TY	NUMERIC(38,2)
,SPEND_BABYGIRL_TY	NUMERIC(38,2)
,SPEND_BABYBOY_TY	NUMERIC(38,2)
,SPEND_BIGGIRL_TY	NUMERIC(38,2)
,SPEND_BIGBOY_TY	NUMERIC(38,2)
,SPEND_ACCESSORIES_TY	NUMERIC(38,2)
,SPEND_SHOES_TY	NUMERIC(38,2)
,LIFECYCLE	VARCHAR(15)
,LIFECYCLE_TCP	VARCHAR(15)
,LIFECYCLE_GYM	VARCHAR(15)
,LIFESTAGE	VARCHAR(15)
,CUST_BIRTHDAY	VARCHAR(15)
,CHILD1_NAME	VARCHAR(32)
,CHILD1_BIRTH_YYYYMM	VARCHAR(15)
,CHILD2_NAME	VARCHAR(32)
,CHILD2_BIRTH_YYYYMM	VARCHAR(15)
,CHILD3_NAME	VARCHAR(32)
,CHILD3_BIRTH__YYYYMM	VARCHAR(15)
,CHILD4_NAME	VARCHAR(32)
,CHILD4_BIRTH_YYYYMM	VARCHAR(15)
,NUM_EMAILS	INTEGER
,NUM_TELECOM	INTEGER
,NUM_CHILDREN	INTEGER
,NUM_GIRLS	INTEGER
,NUM_BOYS	INTEGER
,ACQUISITION_CHANNEL	CHAR
,ACQUISITION_DEVICE_TYPE	VARCHAR(2)
,ACQUISITION_LAST_TOUCH_CHANNEL	VARCHAR(2)
,ACQUISITION_CAMPAIGN_ID	VARCHAR(2)
,ACQUISITION_STORE	VARCHAR(2)
,FIRST_PURCH_DT_TY	DATE
,FIRST_PURCH_DT_US_TY	DATE
,FIRST_PURCH_DT_STORE_US_TY	DATE
,FIRST_PURCH_DT_ECOM_US_TY	DATE
,FIRST_PURCH_DT_CA_TY	DATE
,FIRST_PURCH_DT_STORE_CA_TY	DATE
,FIRST_PURCH_DT_ECOM_CA_TY	DATE
,FIRST_PURCH_DT_LY	DATE
,FIRST_PURCH_DT_US_LY	DATE
,FIRST_PURCH_DT_STORE_US_LY	DATE
,FIRST_PURCH_DT_ECOM_US_LY	DATE
,FIRST_PURCH_DT_CA_LY	DATE
,FIRST_PURCH_DT_STORE_CA_LY	DATE
,FIRST_PURCH_DT_ECOM_CA_LY	DATE
,FIRST_PURCH_DT_LLY	DATE
,FIRST_PURCH_DT_US_LLY	DATE
,FIRST_PURCH_DT_STORE_US_LLY	DATE
,FIRST_PURCH_DT_ECOM_US_LLY	DATE
,FIRST_PURCH_DT_CA_LLY	DATE
,FIRST_PURCH_DT_STORE_CA_LLY	DATE
,FIRST_PURCH_DT_ECOM_CA_LLY	DATE
,PLCC_IND	VARCHAR(2)
,LST_ENROLL_PLCC_TMSTMP	TIMESTAMP
,PLCC_ACCT_KEY	VARCHAR(2)
,PLCC_CREATE_DT	DATE
,CARD_ISSUE_DATE	DATE
,PLCC_OPEN_DT	DATE
,LST_ENROLL_MYPLCE_TMSTMP	TIMESTAMP
,MPR_IND	VARCHAR(2)
,MPR_ACCT_KEY	VARCHAR(2)
,MPR_ACCOUNT_STATUS	VARCHAR(2)
,MYPLACE_ACCT_NBR	VARCHAR(30)
,FAVORITE_STORE_ID	INTEGER
,NEAREST_STORE_ID	INTEGER
,NEAREST_STORE_DISTANCE	INTEGER
,ENROLLMENT_STORE_ID	INTEGER
,PREFERRED_STORE_ID	INTEGER
,PREFERRED_STORE_DISTANCE	INTEGER
,WCS_USER_ID	VARCHAR(2)
,SHOPPER_TYPE	VARCHAR(50)
,CURRENT_PT_BALANCE_CNT	INTEGER
,PTS_TO_NEXT_REWARD	INTEGER
,PTS_EXPIRY_THIS_MONTH	INTEGER
,PTS_EXPIRY_MONTH	INTEGER
,BEST_TELECOM_ID_FOR_CUST	INTEGER
,BEST_EMAIL_ID_FOR_CUST	INTEGER
,COUNTRY	VARCHAR(3)
,DIVISION	VARCHAR(2)
,LANGUAGE	VARCHAR(41)
,CUST_TOTAL_EMAIL	INTEGER
,CUST_TOTAL_TELECOM	INTEGER
,CUST_TOTAL_EMAIL_RESPONSES_6M	INTEGER
,CUST_TOTAL_SMS_CLICKS_6M	INTEGER
,CUST_EMAIL_ACTIVITY_RATIO	INTEGER
,CUST_SMS_ACTIVITY_RATIO	INTEGER
,CUST_CHANNEL_PROPENSITY	INTEGER
)