create table crmdbprd.dsc_dtl
(
	dsc_dtl_id integer not null,
	range_yr varchar(4) ,
	range_mth varchar(2) ,
	dsc_id integer ,
	person_id integer,
	email_addr varchar(75),
	unique_cd varchar(25),
	pos_dsc_cd varchar(25),
	wcs_dsc_cd varchar(25),
	pos_max_usage_cnt smallint,
	wcs_max_usage_cnt smallint,
	pos_usage_cnt smallint,
	pos_start_tmstmp timestamp,
	pos_end_tmstmp timestamp,
	wcs_usage_cnt smallint,
	wcs_start_tmstmp timestamp,
	wcs_end_tmstmp timestamp,
	lst_usage_tmstmp timestamp,
	lst_usage_tmday_id varchar(10),
	lst_usage_store_id varchar(10),
	lst_usage_trn_nbr varchar(15),
	lst_usage_rgstr_nbr varchar(5),
	lst_try_tmstmp timestamp,
	lst_try_tmday_id varchar(10),
	lst_try_store_id varchar(10),
	lst_try_trn_nbr varchar(15),
	lst_try_rgstr_nbr varchar(5),
	lst_try_return_cd varchar(8),
	export_to_eml_tmstmp timestamp,
	import_from_eml_tmstmp timestamp,
	crt_tmstmp timestamp ,
	mdf_tmstmp timestamp ,
	issue_trn_nbr varchar(15),
	cmpgn_wave_id varchar(15),
	myplace_acct_id integer,
	src_id	varchar(50),
	crm_create_tmstmp	timestamp,
	crm_mod_tmstmp	timestamp,
	primary key(dsc_dtl_id)
)
distkey(dsc_dtl_id);

create table crmdbprd.dim_coupon
(
	coupon_id_pk varchar(15) not null,
	company_number varchar(2) not null,
	division_number varchar(2) not null,
	coupon_code varchar(3) not null,
	coupon_effective_start_date date ,
	coupon_start_date date not null,
	coupon_effective_end_date date ,
	coupon_end_date date not null,
	coupon_desc varchar(16),
	coupon_supplemental_desc varchar(16),
	coupon_discount_type_code varchar(1),
	coupon_discount_type_desc varchar(20),
	minimum_coupon_discount_value numeric(8,2),
	maximum_coupon_discount_value numeric(8,2),
	active_indicator varchar(1),
	customer_barcode_scan_ind varchar(1),
	tlog_dsc_id varchar(5),
	dwh_last_modified_timestamp timestamp,
	sku_sub_season_code varchar(2),
	fiscal_year varchar(4),
	fiscal_quarter varchar(5),
	mail_discount_circulation_qty integer,
	email_discount_circulation_qty integer,
	discount_category_lkp_name varchar(35),
	discount_sub_category_lkp_name varchar(35),
	discount_category_lkp_id integer,
	discount_sub_category_lkp_id integer,
	src_id	varchar(50),
	crm_create_tmstmp	timestamp,
	crm_mod_tmstmp	timestamp,
	primary key(coupon_id_pk)
)
distkey(coupon_id_pk);



