create table crm_warehouse.plan_data(
Brand varchar(10),
Type varchar(10),
Country varchar(10),
Last_Touch_Channel varchar(25),
Fiscal_Year varchar(7),
Fiscal_Month varchar(7),
Fiscal_Quarter varchar(7),
FiscalWeek varchar(3),
FiscalWeekISO varchar(7),
Sessions decimal(32,5),
Revenue decimal(32,5),
Orders decimal(32,5),
Units decimal(32,5),
Cogs decimal(32,5),
Cost_TY decimal(32,5),
Cost_LY decimal(32,5),
Cost_PL decimal(32,5),
AcquisitionCust varchar(25),
RetentionCust varchar(25),
ReactivationCust varchar(25),
AcquisitionNewSales decimal(32,5),
AcquisitionSales decimal(32,5),
AcqRolling365sales decimal(32,5),
RetentionSales decimal(32,5),
Reactivation_Sales decimal(32,5),
src_id varchar(25),
crm_create_tmstmp timestamp,
crm_mod_tmstmp timestamp);


