CREATE TABLE crmdbstg.STG_CURRENCY_CON(
	FROM_CURRENCY_CODE	VARCHAR(256),
	TO_CURRENCY_CODE	VARCHAR(256),
	CURRENCY_DT	TIMESTAMP,
	CURRENCY_DAY_EXCH_RT	VARCHAR(256),
	SRC_ID	VARCHAR(50),
	CRM_CREATE_TMSTMP TIMESTAMP,
	CRM_MOD_TMSTMP TIMESTAMP);