
/*File name mapped to the table : BRIGHT_VERIFY%*/

CREATE TABLE crmdbstg.STG_BRITE_VERIFY_RESULTS_STATUS (
	EMAIL_ADDR VARCHAR(126),
	EMAIL_HASHKEY	VARCHAR(100),
	STATUS_DATE	VARCHAR(50),	
	EMAIL_STATUS	VARCHAR(300),
	SECONDARY_STATUS	VARCHAR(300),
	VALID_IND	VARCHAR(10),
	); 
	